### ISSUE TITLE
Notion inconnue

### ISSUE THREAD

**Issue by xamidev** [furtest/revision_ds_algo#1]
Dans `sujet.md` apparaît une notion non vue en cours : `enum`

```c
typedef struct _note{
    enum matieres matiere;
    // ... 
} Note;
```

De même dans

```c
enum matieres matiere;
printf("Choisissez la matiere :\n"
        "1 - Maths\n"
        "2 - Physique\n"
        "3 - Algo\n"
        "4 - Webdev\n"
        "5 - Reseau\n"
        "6 - SHES\n"
        "7 - Autre\n"
        ">>> ");
scanf("%d", &matiere);
```

Peut-être à remplacer par des directives de préprocesseur `#define` vues en cours ?

**Comment by furtest** [comment]
Le code pour les parties utilisant les enum est donné. J'ai ajouté une précision dans le sujet.
